# Generated by Django 4.2.10 on 2024-02-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_remove_blogindexpage_subheadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='main_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
