# Generated by Django 4.2.10 on 2024-02-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='tag_line',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
