# Generated by Django 4.2.10 on 2024-02-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpage_tag_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='blog_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
