# Generated by Django 4.2.10 on 2024-02-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpage_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
