# Generated by Django 4.2.10 on 2024-02-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpage_author_blogpage_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
